version: "3.8"

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: <%= lowercaseName %>
    volumes:
      - ./wp:/var/www/html
      - ./dist:/var/www/html/wp-content/plugins/<%= lowercaseName %>

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: <%= lowercaseName %>
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - wordpress-db:/var/lib/mysql

volumes:
  wordpress-db:
